/**
 * WCAG 2.1 AA audit for the configured site (see college.json at the repo root)
 * Run: node audit/axe-audit.mjs
 * Output: timestamped artifacts in audit/reports/ + human summary on stdout.
 *
 * Artifacts (flat, one set per run — regenerated in place on each run):
 *   audit/reports/axe-<stamp>.json   machine-readable summary for all pages
 *   audit/reports/pages/<slug>.html  per-page standalone audit report
 *                                    (generated by axe-html-reporter)
 */
import { chromium } from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import { createHtmlReport } from 'axe-html-reporter';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'url';
import config from './config.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPORTS = path.join(__dirname, 'reports');
fs.mkdirSync(REPORTS, { recursive: true });

const BASE = config.baseUrl;
const TAGS = ['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'];
const SEVERITY_ORDER = ['critical', 'serious', 'moderate', 'minor'];

// slug from a URL path: /about/frcc-foundation/giving/donate.html -> about-frcc-foundation-giving-donate
function slugFor(url) {
  const p = new URL(url).pathname;
  const s = p.replace(/^\//, '').replace(/\/+$/, '').replace(/[^a-zA-Z0-9-]+/g, '-');
  return s || 'home';
}

async function auditPage(browser, url) {
  const context = await browser.newContext({
    userAgent:
      'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36',
  });
  const page = await context.newPage();
  try {
    const response = await page.goto(url, { waitUntil: 'domcontentloaded', timeout: 45000 });
    const status = response ? response.status() : null;
    // Non-2xx responses (403 WAF block, 404, 5xx) are NOT the real page content.
    // Auditing them would report axe findings on an error/WAF page and count the
    // page as "audited." Record the status and skip analysis so the site builder
    // can surface it as a caveat instead of silently miscounting it.
    if (status != null && (status < 200 || status >= 400)) {
      return {
        url,
        status,
        title: null,
        finalUrl: page.url(),
        slug: slugFor(url),
        blocked: true,
        error: `HTTP ${status}`,
        violations: [],
        violationTotal: 0,
        incomplete: [],
      };
    }
    // Give lazy hydration / SPAs a beat before analyzing (SPA false-negative guard)
    await page.waitForLoadState('networkidle', { timeout: 15000 }).catch(() => {});
    await page.waitForTimeout(1500);

    const results = await new AxeBuilder({ page })
      .withTags(TAGS)
      .analyze();

    const violations = results.violations.map((v) => ({
      id: v.id,
      impact: v.impact,
      help: v.help,
      helpUrl: v.helpUrl,
      wcag: v.tags.filter((t) => /^wcag\d/.test(t)),
      nodes: v.nodes.length,
      firstTargets: v.nodes.slice(0, 5).map((n) => n.target.join(' ')),
    }));
    const incomplete = results.incomplete.map((v) => ({
      id: v.id,
      impact: v.impact,
      help: v.help,
      wcag: v.tags.filter((t) => /^wcag\d/.test(t)),
      nodes: v.nodes.length,
      firstTargets: v.nodes.slice(0, 3).map((n) => n.target.join(' ')),
    }));

    return {
      url,
      title: await page.title().catch(() => null),
      finalUrl: page.url(),
      slug: slugFor(url),
      violations,
      violationTotal: violations.reduce((n, v) => n + v.nodes, 0),
      incomplete,
      raw: results, // full aXe results — powers the per-page HTML report
    };
  } finally {
    await context.close();
  }
}

function printSummary(pages) {
  console.log('\n=== WCAG 2.1 AA AUDIT SUMMARY ===\n');
  const allRules = new Map();
  for (const p of pages) {
    console.log(`\n## ${p.url}${p.title ? ` — "${p.title}"` : ''}`);
    if (p.blocked || p.error) {
      if (p.blocked) console.log(`  SKIP — not audited (HTTP ${p.status})`);
      else console.log(`  SKIP — not audited (load failed: ${String(p.error).slice(0, 80)})`);
      continue;
    }
    if (p.violations.length === 0) {
      console.log('  No axe violations found.');
      continue;
    }
    let total = 0;
    for (const sev of SEVERITY_ORDER) {
      const vs = p.violations.filter((v) => v.impact === sev);
      if (!vs.length) continue;
      for (const v of vs) {
        total += v.nodes;
        allRules.set(v.id, (allRules.get(v.id) || 0) + v.nodes);
        console.log(`  [${sev}] ${v.id} (${v.nodes}x) — ${v.help}`);
        console.log(`     WCAG: ${v.wcag.join(', ')}`);
        console.log(`     e.g. ${v.firstTargets.slice(0, 2).join('  |  ')}`);
      }
    }
    console.log(`  → ${total} node-level violations across ${p.violations.length} rules`);
    if (p.incomplete) console.log(`  → ${p.incomplete} incomplete (needs manual review)`);
  }
  console.log('\n=== RULES BY TOTAL NODE COUNT (all pages) ===');
  const sorted = [...allRules.entries()].sort((a, b) => b[1] - a[1]);
  for (const [id, n] of sorted) console.log(`  ${id}: ${n}`);
}

// Target URLs, highest precedence first:
//   1. Explicit CLI args  ->  node audit/axe-audit.mjs <url> [url...]
//   2. audit/pages.json   ->  { baseUrl, pages: [path | url | { path|url, ... }] }
//   3. Legacy hardcoded fallback
const PAGES_CONFIG = path.join(__dirname, 'pages.json');
function loadTargetUrls(cliArgs) {
  if (cliArgs.length) return cliArgs;
  if (fs.existsSync(PAGES_CONFIG)) {
    const cfg = JSON.parse(fs.readFileSync(PAGES_CONFIG, 'utf8'));
    const base = cfg.baseUrl || BASE;
    const urls = (cfg.pages || []).map((p) =>
      typeof p === 'string'
        ? /^https?:/i.test(p)
          ? p
          : new URL(p, base).toString()
        : p.url
          ? p.url
          : new URL(p.path, base).toString(),
    );
    if (urls.length) return [...new Set(urls)];
  }
  return [BASE, `${BASE}/about`, `${BASE}/admissions`, `${BASE}/programs`];
}
const targetUrls = loadTargetUrls(process.argv.slice(2));

const browser = await chromium.launch();
const pages = [];
for (const url of targetUrls) {
  process.stderr.write(`Auditing ${url} ...\n`);
  try {
    pages.push(await auditPage(browser, url));
  } catch (e) {
    pages.push({
      url,
      status: null,
      title: null,
      finalUrl: url,
      slug: slugFor(url),
      error: String(e),
      violations: [],
      violationTotal: 0,
      incomplete: [],
    });
    console.error(`  FAILED: ${e}`);
  }
}
await browser.close();

// Write artifacts: flat, latest-first (axe-*.json glob stays stable).
//   audit/reports/axe-<stamp>.json      machine-readable summary for all pages
//   audit/reports/pages/<slug>.html     per-page standalone report (axe-html-reporter)
// The full raw aXe results feed the per-page HTML but are not persisted
// separately — at ~300KB/page they would bloat the results repo.
const generated = new Date().toISOString();
const stamp = generated.replace(/[:.]/g, '-');
fs.mkdirSync(path.join(REPORTS, 'pages'), { recursive: true });

const pagesHtml = {};
for (const p of pages) {
  if (p.raw && p.slug) {
    fs.writeFileSync(
      path.join(REPORTS, 'pages', `${p.slug}.html`),
      createHtmlReport({ results: p.raw, options: { doNotCreateReportFile: true } }),
    );
    pagesHtml[p.url] = `pages/${p.slug}.html`;
  }
  delete p.raw; // keep the persisted main report slim
}

const out = path.join(REPORTS, `axe-${stamp}.json`);
fs.writeFileSync(out, JSON.stringify({ generated, tags: TAGS, pages, pagesHtml }, null, 2));
printSummary(pages);
console.log(`\nFull report: ${out}`);
console.log(`Per-page reports: ${path.join(REPORTS, 'pages')} (${Object.keys(pagesHtml).length})`);
